version: 3

tasks:
  add-targets:
    cmds:
      - rustup target add aarch64-apple-darwin
      - rustup target add x86_64-unknown-linux-musl

  setup-linux:
    cmds:
      - task: add-targets
      - sudo apt-get install -y musl-tools

  build:
    cmds:
      - cargo build

  build-amd64-linux:
    cmds:
      - CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl

  build-arm64-darwin:
    cmds:
      - cargo build --release --target aarch64-apple-darwin

  run:
    cmds:
      - cargo run -q -- --exif tests/inputs/exif-jpg.txt --pattern "{y}{m}{D}_{t}_{T2}_{r}.{e}"

  test:
    cmds:
      - cargo test
