version: 3

tasks:
  build:
    cmds:
      - cargo build

  run:
    cmds:
      - cargo run -q -- --exif tests/inputs/exif-jpg.txt --pattern "{y}{m}{D}_{t}_{T2}_{r}.{e}"

  test:
    cmds:
      - cargo test
